name: Black Duck Polaris Full Scan

on:
  push:
    branches: [ "main", "master" , "dependabot/github_actions/devops-infra/action-pull-request-1.4.0" ]

jobs:
  polaris-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Black Duck Security Scan
        uses: blackduck-inc/black-duck-security-scan@v2
        with:
          polaris_server_url: ${{ secrets.POLARIS_SERVER_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polaris_assessment_types: "SAST,SCA" # Options: SAST, SCA, DAST
